import { createRequestHandler } from "@remix-run/cloudflare";
import type { ServerBuild } from "@remix-run/cloudflare";
// @ts-expect-error The Remix server build is generated by `npm run build`.
import * as build from "./build/server/index.js";

type Env = {
  DB?: D1Database;
  SESSION_SECRET?: string;
};

const handleRemixRequest = createRequestHandler(build as unknown as ServerBuild, "production");

export default {
  fetch(request: Request, env: Env, ctx: ExecutionContext) {
    return handleRemixRequest(request, {
      cloudflare: { env, ctx },
      env,
      ctx
    });
  }
};
