# Auto-used by generate_smb_manifest_calculators.py — slug -> engine kind (smb-generic-calc.js)
SLUG_KIND = {
    "budget": "budget",
    "build-or-buy": "build_buy",
    "burn-rate": "burn",
    "burndown-chart": "burndown",
    "business-budget": "budget",
    "business-loan": "loan_pmt",
    "business-valuation": "valuation_multiple",
    "california-sales-tax": "sales_tax",
    "car-depreciation": "car_depreciation",
    "cash-conversion-cycle": "ccc",
    "cash-flow-to-debt": "ratio",
    "cash-ratio": "ratio",
    "churn-rate": "churn",
    "commission": "commission_pct",
    "cost-of-capital": "cost_capital_simple",
    "cost-of-doing-business": "cost_of_doing_business",
    "cost-of-equity": "cost_equity_capm",
    "cpa": "cpa",
    "cpc-cpm": "cpc_cpm",
    "cpm": "cpm",
    "cross-price-elasticity": "elasticity",
    "days-inventory-outstanding": "dio",
    "days-sales-outstanding": "dso",
    "dcf": "dcf_gordon",
    "deadweight-loss": "deadweight",
    "debt": "debt_total_interest",
    "debt-avalanche": "avalanche",
    "debt-consolidation": "debt_consolidation",
    "debt-payoff": "debt_payoff",
    "debt-snowball": "snowball",
    "debt-to-asset": "ratio",
    "debt-to-capital": "ratio",
    "debt-to-equity": "ratio",
    "deferred-payment-loan": "deferred_loan",
    "degree-of-operating-leverage": "dol",
    "depreciation": "depreciation_sl",
    "direct-material-price-variance": "material_variance",
    "discount": "discount_single",
    "discount-rate": "discount_rate",
    "divdend-discount-model": "ddm",
    "double-discount": "discount_double",
    "ebit": "ebit",
    "ebitda": "ebitda",
    "ebitda-multiple": "ebitda_multiple",
    "economic-injury-disaster-loan": "loan_pmt",
    "economic-profit": "economic_profit",
    "ending-inventory": "ending_inventory",
    "ev-to-sales": "ev_sales",
    "expense-ratio": "expense_ratio",
    "fifo-for-inventories": "fifo_simple",
    "financial-leverage-ratio": "financial_leverage",
    "fixed-asset-turnover": "ratio",
    "florida-sales-tax": "sales_tax",
    "free-cash-flow": "fcf",
    "free-cash-flow-to-equity": "fcfe",
    "free-cash-flow-to-firm": "fcff",
    "futures-contract": "futures",
    "gmroi": "gmroi",
    "gross-rent-multiplier": "grm",
    "gross-to-net": "gross_to_net",
    "home-improvement-loan": "loan_pmt",
    "hr-software-roi": "roi_pct",
    "income-elasticity-demand": "income_elasticity",
    "interest-coverage-ratio": "interest_coverage",
    "levered-free-cash-flow": "fcfe",
    "loan": "loan_pmt",
    "loan-balance": "loan_balance",
    "loan-comparison": "loan_compare",
    "loan-interest": "simple_interest",
    "loan-payment": "loan_pmt",
    "loan-repayment": "loan_repayment_total",
    "loss-ratio": "loss_ratio",
    "ltv": "ltv",
    "margin": "margin_pct",
    "margin-2-sets": "margin_two_sets",
    "margin-and-vat": "margin_vat",
    "margin-discount": "margin_discount",
    "margin-interest": "margin_interest",
    "margin-of-safety": "mos",
    "margin-sales-tax": "margin_sales_tax",
    "marginal-cost": "marginal",
    "marginal-revenue": "marginal",
    "marketing-conversion": "marketing_conversion",
    "markup": "markup_pct",
    "markup-beta-feedback": "markup_pct",
    "missouri-sales-tax": "sales_tax",
    "modified-irr": "mirr_simple",
    "net-debt": "net_debt",
    "net-income": "net_income",
    "net-operating-assets": "noa",
    "net-operating-income": "noi",
    "net-operating-working-capital": "nowc",
    "net-profit-margin": "net_profit_margin",
    "net-to-gross": "net_to_gross",
    "new-jersey-sales-tax": "sales_tax",
    "ohio-sales-tax": "sales_tax",
    "online-marketing-roi": "roi_pct",
    "operating-asset-turnover": "ratio",
    "operating-cash-flow": "ocf",
    "operating-cash-flow-ratio": "ocf_ratio",
    "operating-margin": "operating_margin",
    "opportunity-cost": "opportunity_cost",
    "optimal-price": "optimal_price",
    "partially-amortized-loan": "partial_loan",
    "payback-period": "payback",
    "percentage-discount": "percentage_discount",
    "pre-and-post-money-valuation": "pre_post",
    "price-elasticity-demand": "elasticity",
    "price-elasticity-supply": "elasticity",
    "price-per-share": "price_per_share",
    "price-per-sqft": "price_per_area",
    "price-per-square-meter": "price_per_area",
    "price-quantity": "revenue_mult",
    "price-to-book-ratio": "pb",
    "price-to-cash-flow-ratio": "pcf",
    "price-to-earnings": "pe",
    "price-to-sales-ratio": "ps",
    "profitability-index": "pi",
    "real-estate-commission": "real_estate_commission",
    "real-estate-commission-vat": "real_estate_commission_vat",
    "receivables-turnover": "ratio",
    "rental-commission": "rental_commission",
    "residual-income": "residual_income",
    "revenue": "revenue",
    "revenue-growth": "revenue_growth",
    "revenue-per-employee": "ratio_mixed",
    "roas": "roas",
    "roi": "roi_pct",
    "roic": "roic",
    "saas-ltv": "saas_ltv",
    "saas-metrics": "saas_metrics",
    "sales": "sales",
    "sales-commission": "commission_pct",
    "sales-tax": "sales_tax",
    "software-contract-value": "scv",
    "times-interest-earned-ratio": "interest_coverage",
    "total-asset-turnover": "ratio",
    "triple-discount": "discount_triple",
    "true-cost-of-real-estate-commission": "true_cost_re",
    "turnover-rate": "turnover_rate",
    "unlevered-free-cash-flow": "fcff",
    "wacc": "wacc",
    "website-ad-revenue": "ad_revenue",
    "working-capital": "working_capital",
    "working-capital-turnover-ratio": "ratio",
}

# slug -> (numerator label, denominator label, primary metric label) for kind "ratio" / ratio_any
RATIO_LABELS = {
    "cash-flow-to-debt": ("Operating cash flow", "Total debt", "Cash flow to debt ratio"),
    "cash-ratio": ("Cash and cash equivalents", "Current liabilities", "Cash ratio"),
    "debt-to-asset": ("Total debt", "Total assets", "Debt-to-asset ratio"),
    "debt-to-capital": ("Total debt", "Total debt + equity (capital)", "Debt-to-capital ratio"),
    "debt-to-equity": ("Total debt", "Total equity", "Debt-to-equity ratio"),
    "fixed-asset-turnover": ("Revenue", "Net fixed assets", "Fixed asset turnover"),
    "operating-asset-turnover": ("Revenue", "Operating assets", "Operating asset turnover"),
    "total-asset-turnover": ("Revenue", "Total assets", "Total asset turnover"),
    "working-capital-turnover-ratio": ("Revenue", "Working capital", "Working capital turnover"),
    "receivables-turnover": ("Revenue (or net credit sales)", "Accounts receivable", "Receivables turnover"),
}

# Kinds that use synced currency selects (money inputs)
CURRENCY_KINDS = frozenset({
    "budget", "build_buy", "burn", "loan_pmt", "loan_balance", "loan_compare", "simple_interest",
    "wacc", "working_capital", "ccc", "ratio", "cpa", "cpm", "cpc", "roas", "commission_pct",
    "discount_single", "discount_double", "discount_triple", "sales_tax", "depreciation_sl",
    "car_depreciation", "material_variance", "ddm", "dcf_gordon", "ebit", "ebitda", "ebitda_multiple",
    "economic_profit", "residual_income", "net_income", "noi", "nowc", "noa", "net_debt", "ev_sales",
    "pe", "pb", "ps", "pcf", "price_per_share", "price_per_area", "revenue_mult", "pre_post", "pi",
    "optimal_price", "margin_discount", "margin_vat", "margin_sales_tax", "margin_two_sets",
    "margin_interest", "debt_consolidation", "deferred_loan", "partial_loan", "ending_inventory",
    "fifo_simple", "ocf", "ocf_ratio", "fcf", "fcfe", "fcff", "loss_ratio", "ltv", "futures", "gmroi",
    "grm", "gross_to_net", "net_to_gross", "saas_ltv", "saas_metrics", "scv", "ad_revenue",
    "debt_payoff", "debt_total_interest", "loan_repayment_total", "revenue", "sales", "percentage_discount",
    "real_estate_commission", "real_estate_commission_vat", "rental_commission", "true_cost_re",
    "avalanche", "snowball", "valuation_multiple", "margin_pct", "markup_pct", "roi_pct", "roic",
    "cost_of_doing_business", "ratio_mixed",
})
